<!-- @format -->

<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction

Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

<!-- @format -->

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones.

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage.

Therefore if we can determine if the first stage will land, we can determine the cost of a launch.

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

<!-- @format -->

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

<a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv" target="_blank">Spacex DataSet</a>

In [13]:
!pip install sqlalchemy==2
!pip install ipython-sql

Requirement already satisfied: sqlalchemy==2 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (2.0.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from sqlalchemy==2) (4.9.0)
Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.9.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: ipython in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython-sql) (8.18.1)
Requirement already satisfied: sqlalchemy>=2.0 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython-sql) (2.0.0)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: six in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython-sql) (1.16.0)
Collecting ipython-genutils (from ipython-sql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.9.0)
Requirement already satisfied: decorator in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (3.0.42)
Requirement already satisfied: pygments>=2.4.0 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (2.17.2)
Requirement already satisfied: stack-data in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (0.6.2)
Requirement already satisfied: traitlets>=5 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (5.14.0)
Requirement already satisfied: pexpect>4.3 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from ipython->ipython-sql) (4.8.0)
Requirement already satisfied: wcwidth in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from prettytable->ipython-sql) (0.2.12)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from stack-data->ipython->ipython-sql) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from stack-data->ipython->ipython-sql) (2.4.1)
Requirement already satisfied: pure-eval in /Users/macjianfeng/miniforge3/envs/spyder-env/lib/python3.11/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Downloading prettytable-3.9.0-py3-none-any.whl (27 kB)
Installing collected packages: ipython-genutils, sqlparse, prettytable, ipython-sql
Successfully installed ipython-genutils-0.2.0 ipython-sql-0.5.0 prettytable-3.9.0 sqlparse-0.4.4

<!-- @format -->

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [14]:
%load_ext sql
%config SqlMagic.autocommit=False # for engines that do not support autommit

In [15]:
import csv, sqlite3

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

In [ ]:
# !pip install -q pandas==1.1.5

In [19]:
%sql sqlite:///my_data1.db

In [29]:
import pandas as pd

df = pd.read_csv(
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv"
)
df.to_sql("SPACEXTBL", con, if_exists="replace", index=False, method="multi")
df

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt
...,...,...,...,...,...,...,...,...,...,...
96,2020-11-05,23:24:23,F9 B5B1062.1,CCAFS SLC-40,"GPS III-04 , Crew-1",4311,MEO,USSF,Success,Success
97,2020-11-16,0:27:00,F9 B5B1061.1,KSC LC-39A,"Crew-1, Sentinel-6 Michael Freilich",12500,LEO (ISS),NASA (CCP),Success,Success
98,2020-11-21,17:17:08,F9 B5B1063.1,VAFB SLC-4E,"Sentinel-6 Michael Freilich, Starlink 15 v1.0",1192,LEO,NASA / NOAA / ESA / EUMETSAT,Success,Success
99,2020-11-25,2:13:00,F9 B5 B1049.7,CCAFS SLC-40,"Starlink 15 v1.0, SpaceX CRS-21",15600,LEO,SpaceX,Success,Success
100,2020-12-06,16:17:08,F9 B5 B1058.4,KSC LC-39A,SpaceX CRS-21,2972,LEO (ISS),NASA (CRS),Success,Success

<!-- @format -->

**Note:This below code is added to remove blank rows from table**

In [39]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

 * sqlite:///my_data1.db
(sqlite3.OperationalError) table SPACEXTABLE already exists
[SQL: create table SPACEXTABLE as select * from SPACEXTBL where Date is not null]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

<!-- @format -->

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

**Note: If the column names are in mixed case enclose it in double quotes
For Example "Landing_Outcome"**

### Task 1

##### Display the names of the unique launch sites in the space mission

In [53]:
tab_SPACEXTABLE = cur.execute("SELECT * FROM SPACEXTABLE")
records = tab_SPACEXTABLE.fetchall()
launchsites = []
for row in records:
    if row[3] not in launchsites:
        launchsites.append(row[3])
launchsites

['CCAFS LC-40', 'VAFB SLC-4E', 'KSC LC-39A', 'CCAFS SLC-40']

<!-- @format -->

### Task 2

##### Display 5 records where launch sites begin with the string 'CCA'

In [127]:
# df[df["Launch_Site"].str.contains("CCA")][:5]
tab_SPACEXTABLE = cur.execute("SELECT * FROM SPACEXTABLE LIMIT 5")
records = tab_SPACEXTABLE.fetchall()
CCA_sites = []
for row in records:
    if row[3] not in CCA_sites:
        CCA_sites.append(row[3])
CCA_sites

['CCAFS LC-40']

<!-- @format -->

### Task 3

##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [71]:
for row in records:
    if row[7] == "NASA (CRS)":
        print("Playload:", row[4], "mass(kg):", row[5])

Playload: SpaceX CRS-1 mass(kg): 500
Playload: SpaceX CRS-2 mass(kg): 677
Playload: SpaceX CRS-3 mass(kg): 2296
Playload: SpaceX CRS-4 mass(kg): 2216
Playload: SpaceX CRS-5 mass(kg): 2395
Playload: SpaceX CRS-6 mass(kg): 1898
Playload: SpaceX CRS-7 mass(kg): 1952
Playload: SpaceX CRS-8 mass(kg): 3136
Playload: SpaceX CRS-9 mass(kg): 2257
Playload: SpaceX CRS-10 mass(kg): 2490
Playload: SpaceX CRS-11 mass(kg): 2708
Playload: SpaceX CRS-12 mass(kg): 3310
Playload: SpaceX CRS-13 mass(kg): 2205
Playload: SpaceX CRS-14 mass(kg): 2647
Playload: SpaceX CRS-15 mass(kg): 2697
Playload: SpaceX CRS-16 mass(kg): 2500
Playload: SpaceX CRS-17, Starlink v0.9 mass(kg): 2495
Playload: SpaceX CRS-18, AMOS-17  mass(kg): 2268
Playload: SpaceX CRS-20, Starlink 5 v1.0  mass(kg): 1977
Playload: SpaceX CRS-21 mass(kg): 2972

<!-- @format -->

### Task 4

##### Display average payload mass carried by booster version F9 v1.1

In [156]:
a = df[df["Booster_Version"].str.contains("F9 v1.1")].describe()

tab_SPACEXTABLE = cur.execute(
    "SELECT AVG(PAYLOAD_MASS__KG_) FROM SPACEXTABLE WHERE Booster_Version LIKE 'F9 v1.1' "
)

records = tab_SPACEXTABLE.fetchall()
print(records, a)

[(2928.4,)]        PAYLOAD_MASS__KG_
count          15.000000
mean         2534.666667
std          1471.311546
min           500.000000
25%          1607.000000
50%          2296.000000
75%          3742.000000
max          4707.000000

<!-- @format -->

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.

_Hint:Use min function_

In [164]:
# df.shape[0]
tab_SPACEXTABLE = cur.execute(
    "SELECT Date FROM SPACEXTABLE WHERE Landing_Outcome  = 'Success' LIMIT 4"
)

records = tab_SPACEXTABLE.fetchall()
print(records)

[('2018-07-22',), ('2018-07-25',), ('2018-08-07',), ('2018-09-10',)]

In [117]:
for i in range(df.shape[0]):
    if df.loc[i, "Landing_Outcome"] == "Success":
        print(df.loc[i, "Date"])
        break

2018-07-22

<!-- @format -->

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [125]:
df
j = []
for i in range(df.shape[0]):
    if (
        df.loc[i, "Landing_Outcome"] == "Success"
        and 4000 < df.loc[i, "PAYLOAD_MASS__KG_"] < 6000
    ):
        j.append(i)
df_suc = df.loc[j, "Booster_Version"].unique()
print(df_suc, df_suc.shape)

['F9 B5 B1046.2' 'F9 B5 B1047.2' 'F9 B5 B1048.3' 'F9 B5 B1051.2 '
 'F9 B5B1060.1' 'F9 B5 B1058.2 ' 'F9 B5B1062.1'] (7,)

In [172]:
tab_SPACEXTABLE = cur.execute(
    "SELECT Booster_Version, PAYLOAD_MASS__KG_ FROM SPACEXTABLE"
)
records = tab_SPACEXTABLE.fetchall()
# print(records)
res = []
for row in records:
    if 4000 < row[1] < 6000:
        res.append(row[0])
        print("\n", row[0])

 F9 v1.1

 F9 v1.1 B1011

 F9 v1.1 B1014

 F9 v1.1 B1016

 F9 FT B1020

 F9 FT B1022

 F9 FT B1026

 F9 FT B1030

 F9 FT  B1021.2

 F9 FT B1032.1

 F9 B4 B1040.1

 F9 FT  B1031.2

 F9 B4 B1043.1

 F9 FT  B1032.2

 F9 B4  B1040.2

 F9 B5 B1046.2

 F9 B5 B1047.2

 F9 B5B1054

 F9 B5 B1048.3

 F9 B5 B1051.2

 F9 B5B1060.1

 F9 B5 B1058.2

 F9 B5B1062.1

<!-- @format -->

### Task 7

##### List the total number of successful and failure mission outcomes

In [187]:
tab_SPACEXTABLE_no_succ = cur.execute(
    "SELECT Mission_Outcome FROM SPACEXTABLE WHERE Mission_Outcome != 'Success' "
)
records_no_succ = tab_SPACEXTABLE_no_succ.fetchall()
print(len(records_no_succ))

tab_SPACEXTABLE_succ = cur.execute(
    "SELECT Mission_Outcome FROM SPACEXTABLE WHERE Mission_Outcome = 'Success' "
)
records_succ = tab_SPACEXTABLE_succ.fetchall()
print(len(records_succ))

3
98

<!-- @format -->

### Task 8

##### List the names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [197]:
tab_SPACEXTABLE = cur.execute(
    "SELECT Booster_Version, PAYLOAD_MASS__KG_ FROM SPACEXTABLE"
)
records = tab_SPACEXTABLE.fetchall()

# !pip install operator
from operator import itemgetter

max(records, key=itemgetter(1))

('F9 B5 B1048.4', 15600)

In [214]:
df

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
0,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt
...,...,...,...,...,...,...,...,...,...,...
96,2020-11-05,23:24:23,F9 B5B1062.1,CCAFS SLC-40,"GPS III-04 , Crew-1",4311,MEO,USSF,Success,Success
97,2020-11-16,0:27:00,F9 B5B1061.1,KSC LC-39A,"Crew-1, Sentinel-6 Michael Freilich",12500,LEO (ISS),NASA (CCP),Success,Success
98,2020-11-21,17:17:08,F9 B5B1063.1,VAFB SLC-4E,"Sentinel-6 Michael Freilich, Starlink 15 v1.0",1192,LEO,NASA / NOAA / ESA / EUMETSAT,Success,Success
99,2020-11-25,2:13:00,F9 B5 B1049.7,CCAFS SLC-40,"Starlink 15 v1.0, SpaceX CRS-21",15600,LEO,SpaceX,Success,Success
100,2020-12-06,16:17:08,F9 B5 B1058.4,KSC LC-39A,SpaceX CRS-21,2972,LEO (ISS),NASA (CRS),Success,Success

In [230]:
df3.index.values
df4

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing_Outcome
13,2015-01-10,9:47:00,F9 v1.1 B1012,CCAFS LC-40,SpaceX CRS-5,2395,LEO (ISS),NASA (CRS),Success,Failure (drone ship)
14,2015-02-11,23:03:00,F9 v1.1 B1013,CCAFS LC-40,DSCOVR,570,HEO,U.S. Air Force NASA NOAA,Success,Controlled (ocean)
15,2015-03-02,3:50:00,F9 v1.1 B1014,CCAFS LC-40,ABS-3A Eutelsat 115 West B,4159,GTO,ABS Eutelsat,Success,No attempt
16,2015-04-14,20:10:00,F9 v1.1 B1015,CCAFS LC-40,SpaceX CRS-6,1898,LEO (ISS),NASA (CRS),Success,Failure (drone ship)
17,2015-04-27,23:03:00,F9 v1.1 B1016,CCAFS LC-40,Turkmen 52 / MonacoSAT,4707,GTO,Turkmenistan National Space Agency,Success,No attempt
18,2015-06-28,14:21:00,F9 v1.1 B1018,CCAFS LC-40,SpaceX CRS-7,1952,LEO (ISS),NASA (CRS),Failure (in flight),Precluded (drone ship)
19,2015-12-22,1:29:00,F9 FT B1019,CCAFS LC-40,OG2 Mission 2 11 Orbcomm-OG2 satellites,2034,LEO,Orbcomm,Success,Success (ground pad)

In [229]:
# convert number to month name
!pip install calendar


df3=df[df["Date"].str.contains("2015")]
df4=df3.reindex()
for i in df3.index.values:
    print(i)
    if df3.loc[i,"Landing_Outcome"]!= 'Success':
        print(df3[i,["Booster_Version","Launch_Site"]])

ERROR: Could not find a version that satisfies the requirement calendar (from versions: none)
ERROR: No matching distribution found for calendar
13

InvalidIndexError: (13, ['Booster_Version', 'Launch_Site'])

<!-- @format -->

### Task 9

##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015.

**Note: SQLLite does not support monthnames. So you need to use substr(Date, 6,2) as month to get the months and substr(Date,0,5)='2015' for year.**

In [200]:
tab_SPACEXTABLE = cur.execute("SELECT * FROM SPACEXTABLE WHERE Date LIKE '2015' ")
records = tab_SPACEXTABLE.fetchall()
print(records)

[]

<!-- @format -->

### Task 10

##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order.

<!-- @format -->

### Reference Links

- <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>

- <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

- <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

- <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb">Hands-on Tutorial: Accessing Databases with SQL magic</a>

- <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb">Hands-on Lab: Analyzing a real World Data Set</a>

<!-- @format -->

## Author(s)

<h4> Lakshmi Holla </h4>

<!-- @format -->

## Other Contributors

<h4> Rav Ahuja </h4>

<!-- @format -->

## Change log

| Date       | Version | Changed by    | Change Description        |
| ---------- | ------- | ------------- | ------------------------- |
| 2021-07-09 | 0.2     | Lakshmi Holla | Changes made in magic sql |
| 2021-05-20 | 0.1     | Lakshmi Holla | Created Initial Version   |

<!-- @format -->

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>